library(ggplot2)
data<- read.csv(file='3831assignment.csv',header=TRUE)


```{r}
data<- read.csv(file='3831assignment.csv',header=TRUE)
disdata <- dist(data[,7:10],"manhattan")#calculate distance matrix
data.clst <- hclust(disdata,"average")# hierarchical clustering, complete linkage
plot(data.clst,hang=-1)#plot a dendrogram


cor(data$What.is.your.attitude.towards.online.learning.,data$I.have.access.to.stable.internet.connection.while.accessing.online.learning.)
cor(data$What.is.your.attitude.towards.online.learning.,data$I.have.access.to.suitable.devices.to.meet.the.requirements.for.online.learning)
cor(data$What.is.your.attitude.towards.online.learning.,data$I.am.able.to.stay.focused.and.concentrated.throughout.all.my.online.courses.)
cor(data$What.is.your.attitude.towards.online.learning.,data$I.feel.supported.by.my.course.coordinators..lecturers.and.tutors.through.online.platforms.)
cor(data$What.is.your.attitude.towards.online.learning.,data$The.courses.I.am.undertaking.have.provided.me.resources.to.help.me.learn.online)


library(ggplot2)
barplot(data$What.is.your.current.living.situation.)

```




```{r}
par(mfrow=c(2,3))
boxplot(data$What.is.your.attitude.towards.online.learning.,main="Attitude towards Online learning",col='khaki')
boxplot(data$Online.learning.has.proven.to.be.effective.towards.my.academic.performance., main="Effectiveness of online learning",col='skyblue')
boxplot(data$How.would.you.rank.online.learning..face.to.face.learning.or.hybrid.learning..With.1.being.the.best.and.3.being.the.worst...Online.learning., main="Ranking of online learning",col='darkolivegreen2')
```


```{r}
sort(cor(data[,c(7,8,9,10,11)]))[1:3]
```
```{r}

```

```{r}
par(mfrow=c(1,5),mar=c(1, 1, 3, 2))
boxplot(data$I.have.access.to.stable.internet.connection.while.accessing.online.learning.,main='Stable internet')
boxplot(data$I.have.access.to.suitable.devices.to.meet.the.requirements.for.online.learning,main='Suitable devices')
boxplot(data$I.am.able.to.stay.focused.and.concentrated.throughout.all.my.online.courses.,main='Concentration')
boxplot(data$I.feel.supported.by.my.course.coordinators..lecturers.and.tutors.through.online.platforms.,main='Supportive course coordinators')
boxplot(data$The.courses.I.am.undertaking.have.provided.me.resources.to.help.me.learn.online,main='Sufficient recource')


```
```{r}
factpca <- princomp(data[,7:11],cor=TRUE)
factpca
summary(factpca)
factpca$loadings
cor(data[,7:11])
```
```{r}
temp1<- 7:11
for (i in temp1){print(var(data[,i]))}
```

```{r}

```





```{r}
lm(data[,2]~data[,7]+data[,8]+data[,9]+data[,10]+data[,11])
```
```{r}
datatemp <- data[,7:11]
covmat <- as.matrix(datatemp)
covmat.eig <-eigen(covmat)
plot(covmat.eig$values,,type="b",ylab="Variances",xlab="Principal Component")
```
```{r}
cluster1 <- c(1,	2,	20,	44,	45,	65,	68,	71,	73,	78,	86,	91)
cluster2 <- c(3,	6,	7,	9,	11,	12,	14,	15,	18,	19,	24,	26,	27,	31,	33,	51,	52,	59,	62,	70,	72,	76,	80,	83,	85,	87,	88,	89,	92)
cluster3 <- c(4,	8,	10,	21,	22,	23,	37,	38,	39,	43,	56,	64,	66	,74	,75	,79	,81,	84)
cluster4 <- c(5,	13,	17,	36,	42,	50,	67)
cluster5 <- c(16,	25,	28,	29,	30,	32,	34,	35,	40,	41,	46	,47,	48,	49,	53,	54,	55,	57,	58,	60,	61	,63,	69,	82,	90)
clu1 <- data[cluster1,]
clu2 <- data[cluster2,]
clu3 <- data[cluster3,]
clu4 <- data[cluster4,]
clu5 <- data[cluster5,]

attitudemean <- mean(data$What.is.your.attitude.towards.online.learning.)
xtemp1  <- 1:5
ytemp  <- c(mean(clu1[,2]),mean(clu2[,2]),mean(clu3[,2]),mean(clu4[,2]),mean(clu5[,2]))
plot
plot(xtemp1,ytemp,"p",xlab="Cluster",ylab="Attitude mean")
abline(h=attitudemean,col="red")

```
```{r}
clu2
```
```{r}







```

